### ISSUE TITLE
Assertion fctx->async_lock failed at libavcodec/pthread_frame.c:155

### ISSUE THREAD

**Issue by iBelow** [statueofmike/rtsp#18]
code: 
```
import rtsp

uri = f"rtsp://user:pass@192.168.78.201:554/live"
with rtsp.Client(rtsp_server_uri=uri) as client:
    client.preview()

```
ERROR:

`Assertion fctx->async_lock failed at libavcodec/pthread_frame.c:155`

**Comment by j13tw** [comment]
Hello iBelow,
I doing my python flask project to capture the RTSP Camera have same problem
I think the problem is base on the client = rtsp.Client("rtspUrl") is not ready to connect rtsp server
then the check connection status command "client.isOpened()" is true
and the python code sequence execute the client.preview() command to read the rtsp video frame 
so when you call the function client.preview() or client.read().save() 
it will alert the thread fail message on terminal
in my solution to fix it, 
i import "time" package and add the "time.sleep(1)" to wait the connection

```
import rtsp
import time

uri = f"rtsp://10.0.0.160:554/live.sdp"
with rtsp.Client(rtsp_server_uri=uri) as client:
    time.sleep(1)
    client.preview()
```

**Comment by iBelow** [comment]
> Hello iBelow,
> I doing my python flask project to capture the RTSP Camera have same problem
> I think the problem is base on the client = rtsp.Client("rtspUrl") is not ready to connect rtsp server
> then the check connection status command "client.isOpened()" is true
> and the python code sequence execute the client.preview() command to read the rtsp video frame
> so when you call the function client.preview() or client.read().save()
> it will alert the thread fail message on terminal
> in my solution to fix it,
> i import "time" package and add the "time.sleep(1)" to wait the connection
> 
> ```
> import rtsp
> import time
> 
> uri = f"rtsp://10.0.0.160:554/live.sdp"
> with rtsp.Client(rtsp_server_uri=uri) as client:
>     time.sleep(1)
>     client.preview()
> ```
Thanx!

**Comment by garudaonekh** [comment]
Add time.sleep(1) does solve the above Assertion, but the gunicorn consumes too much CPU 90-100% and start spawning new PID:
 gunicorn[32285]: [2021-07-06 22:47:08 +0700] [13893] [INFO] Booting worker with pid: 13893.


Any suggestion?
