### ISSUE TITLE
Keep RTSP connection alive

### ISSUE THREAD

**Issue by learnermaxRL** [statueofmike/rtsp#6]
Can you tell me how to keep the rtsp connection alive,my connection keep dropping after 10-15 seconds consistently

**Comment by dactylroot** [comment]
Try using the package with "verbose=True", and also check what version you
are using. The newest version v1.1.4 makes a new connection every time a
read occurs to avoid buffer issues, while v1.1.3 tries to keep the
connection alive all the time.

--
Michael

**Comment by learnermaxRL** [comment]
Not working,I am on latest version still connection closes after few seconds

**Comment by shadow7412** [comment]
@statueofmike would you be able to make this an option rather than forcing a reconnection every time?
This seems to be severely affecting my possible framerate...

**Comment by drakorg** [comment]
I agree. Making a new connection for every read in order to avoid buffering
issues is a little too drastic if you ask me. It makes the library unusable
in practice: there's no way you could ever get any decent frame rate in any
scenario with that approach.

I'm personally holding to one or the first versions of the project when it
still had a thread that was permanently fetching frames and you always had
the last frame fetched easily available for quick access. The only pitfall
with that version was that it would lose the connection after n dropped
frames (and sadly not reconnect again after that).. but that could have
been easily solved.

Very useful and simple library, I just dont agree with the latest criteria
of making a new connection for every read.

It will just never work for me. I wonder if for anyone.

**Comment by dactylroot** [comment]
Making it configurable is doable, but I don't know how much time I'll have to make the connection robust.

**Comment by dactylroot** [comment]
closing per f9ddb7be9612e150e89105c821d23c0d1669ef17

please let me know any suggestions here or for #13, which was why I closed the connection earlier
